---
# Copyright: (c) 2023, Red Hat
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
argument_specs:
  main:
    version_added: 1.0.0
    short_description: Reconfigures rendezvous server files.
    description:
      - Deploy and configure FDO Rendezvous server 
    options:
      fdo_src:
        description:
          - Fdo directory path.
        type: str
        default: /etc/fdo
      manufacturing_server_fdo_src:
        description:
          - Fdo directory path on the manufacturing server.
        type: str
        default: /etc/fdo
      manufacturing_server:
        description:
          - Manufacturing Server.
        type: str
        default: "{{ groups['manufacturing'][0] }}"
      copy_manufacturer_certs:
        description:
          - Enable fetching manufacturing server certificates & keys.
        type: bool
        default: true  
      rpm:
        description:
        - Deploy as RPM package
        type: bool
      rendezvous_server_storage_driver_path:
        description:
          - Rendezvous server storage directory path.
        type: str
        default: "{{ fdo_src }}/stores/rendezvous_registered"
      rendezvous_server_session_store_driver_path:
        description:
          - Rendezvous server sessions directory path.
        type: str
        default: "{{ fdo_src }}/stores/rendezvous_sessions"
      rendezvous_server_trusted_manufacturer_keys_path:
        description:
          - manufacturer_cert.pem file path.
        type: str
        default: "{{ fdo_src }}/keys/manufacturer_cert.pem"
      rendezvous_server_max_wait_seconds:
        description:
          - Rendezvous server max wait time in seconds.
        type: str
        default: ~
      rendezvous_server_bind_ip:
        description:
          - The IP address that the rendezvous server will bind to.
        type: str
        default: 0.0.0.0
      rendezvous_server_listen_port_rendezvous_server:
        description:
          - The port that the rendezvous server will listen to.
        type: int
        default: 8082